# Generated by Django 3.1.2 on 2021-08-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210819_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
