# Generated by Django 3.1.2 on 2021-08-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210820_0415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
